JuiceMitApfelnDrin/CodinCod

.github/README.md

trying to link the readme made in docs to the main readme of codincod

docs: symbolic readme from docs in codincod

---

libs/backend/package.json
libs/backend/src/app.ts
pnpm-lock.yaml

added a rate limiter, cus don't want spam? not sure if numbers are dialed in right tho

feat: add rate limiter

---

libs/frontend/src/lib/config/search-params.ts
libs/frontend/src/routes/(authenticated)/+layout.server.ts
libs/frontend/src/routes/(unauthenticated-only)/login/+page.server.ts

branched of from [rate-limit](https://github.com/JuiceMitApfelnDrin/CodinCod/pull/11), review that one first 
now when you're not logged in and get redirected to the login screen, when you login, you get thrown back to the page you wanted to go to

feat: add redirect url on log in

---

docker-compose.yml
libs/frontend/Dockerfile

backseating: origin env var example

---

libs/frontend/src/lib/features/game/components/codemirror.svelte

height of editor too tall

---

libs/backend/src/routes/submission/index.ts
libs/frontend/src/lib/features/puzzles/components/play-puzzle.svelte
libs/types/src/core/puzzle/schema/validator.schema.ts

fix whitespace in validator input/output

---

libs/backend/.env.example
libs/backend/src/app.ts
libs/backend/src/plugins/config/mongoose.ts

feat: set db name in env

---

libs/frontend/package.json
libs/frontend/src/lib/features/game/standings/components/standings-table.svelte
pnpm-lock.yaml

Add hh mm ss to standings table time instead of just when submitted

---

libs/frontend/src/lib/stores/index.ts
libs/frontend/src/routes/+layout.server.ts
libs/frontend/src/routes/+layout.svelte

Hi there, long time no see, prior we might've had a small tiny issue, related to not unsetting the token when the isAutenthicatedInfo is false, i resolved that, so now it should only happen once every 24hrs :pray: , might've fixed another bug, can't remember tbh

fix: access token expired but not visible in frontend issue

---

libs/frontend/src/lib/features/puzzles/components/edit-puzzle-form.svelte
libs/types/src/core/common/config/frontend-urls.ts

I think these descriptions should be better at guiding contributors in the right direction

More instructive puzzle form descriptions

---

libs/backend/package.json
libs/frontend/package.json
libs/types/package.json
pnpm-lock.yaml

Bump zod (#81)

---

libs/frontend/src/lib/features/chat/components/chat-message.svelte
libs/frontend/src/lib/features/chat/components/chat.svelte
libs/frontend/src/lib/features/puzzles/components/edit-puzzle-form.svelte

Fix height out of control issue when you have X amount of messages;
and removal of unused files

Message container height grows after X messages

---

.github/workflows/deploying-to-prod.yml

Previously we had to manually go into the server after building the images, this should do it automagically after every successful build on main

Add deploy to production action

---

libs/frontend/src/routes/(authenticated)/settings/preferences/+page.svelte

Previously, there was no description, this adds one

fix: keymap description

---

libs/frontend/src/routes/(authenticated)/settings/+page.svelte

fixes: https://github.com/JuiceMitApfelnDrin/CodinCod/issues/106

Fix back button in settings issue

---

libs/frontend/src/routes/+page.svelte

I'd like to get current games visible on the landing page too but I think that requires some refactoring of the backend, so I just changed the text for now. Feedback would be appreciated.

More welcoming landing page

---

libs/backend/test/health/index.ts
libs/frontend/src/lib/features/authentication/login/components/login-form.svelte
libs/types/src/core/authentication/config/identifier-config.ts
libs/types/src/index.ts

An identifier to login, can be either an email or a username, only took username into account, neglecting the email length and pattern possibilities

fix: login issue, only taken username length into account

---

libs/backend/src/routes/login/index.ts
libs/backend/test/health/index.ts
libs/frontend/src/lib/features/authentication/login/components/login-form.svelte
libs/types/src/core/authentication/config/email-config.ts
libs/types/src/core/authentication/config/identifier-config.ts
libs/types/src/index.ts

Fix login issue forgotton import of isemail

Fix login issue forgotton import of isemail

---

libs/backend/src/app.ts

refactor: remove unnecessary comments

---

README.md

update readme.md with introduction and table of contents

update readme.md with introduction and table of contents

---

libs/frontend/src/app.css
libs/frontend/src/lib/components/nav/nav.svelte
libs/frontend/src/lib/features/settings/components/side-navigation-settings.svelte

Made it look better for light theme, also added a general font for the whole website.
(not super happy yet with the font, but it's an improvement????)

Fix: side navigation colors on settings

---

libs/frontend/src/lib/features/game/components/codemirror.svelte

cleanup: remove console.log

---

libs/frontend/package.json
libs/frontend/src/lib/components/nav/user-dropdown.svelte
libs/frontend/src/lib/components/ui/avatar/avatar.svelte
libs/frontend/src/lib/components/ui/select/select-item.svelte
libs/frontend/src/lib/components/ui/sonner/index.ts
libs/frontend/src/lib/components/ui/sonner/sonner.svelte
libs/frontend/src/lib/features/game/standings/components/standings-table.svelte
libs/frontend/src/lib/features/puzzles/components/play-puzzle.svelte
libs/frontend/src/lib/features/puzzles/components/puzzle-meta-info.svelte
libs/frontend/src/routes/(authenticated)/puzzles/[id]/edit/+page.server.ts
libs/frontend/src/routes/(authenticated)/puzzles/[id]/edit/+page.svelte
libs/frontend/src/routes/(authenticated)/settings/+page.svelte
libs/frontend/src/routes/+layout.svelte
libs/types/src/core/puzzle/schema/puzzle-entity.schema.ts
pnpm-lock.yaml

You now get a toast when you ran tests, informing you on the updated state
https://github.com/JuiceMitApfelnDrin/CodinCod/issues/78

Feat improved feedback on executing tests

---

libs/frontend/src/lib/features/game/standings/components/standings-table.svelte

fix standings table time sometimes being greater than given time

---

libs/backend/src/models/comment/comment.ts
libs/backend/src/routes/comment/[id]/comment/index.ts
libs/backend/src/routes/comment/[id]/index.ts
libs/backend/src/routes/puzzle/[id]/comment/index.ts
libs/frontend/src/lib/features/comment/components/comment.svelte
libs/frontend/src/lib/features/comment/components/comments.svelte
libs/frontend/src/lib/features/profile/components/activity-group.svelte
libs/frontend/src/routes/api/comment/[id]/+server.ts
libs/types/src/core/comment/schema/comment.schema.ts

Prior to this, we had the ability to spam comments and overflow the users, but i couldn't even delete my own comments.
Now i can, and i am so much more pleased.
Due to implementation choice, when a comment gets deleted, the sub comments also get deleted, we thought about another approach of anonymizing the comment message and author, but ultimately decided to go with this approach :pray: .

feat: add ability to delete comments

---

README.md

fix: README.md url

---

libs/frontend/src/routes/puzzles/[id]/+page.svelte
libs/types/src/core/comment/schema/comment-dto.schema.ts
libs/types/src/core/comment/schema/comment.schema.ts
libs/types/src/core/common/schema/object-id.ts

Urgent bug-fix, caused multiplayer to crash 100/100 times

fix: object-id-schema issue related to previous objectidschema change

---

libs/frontend/src/app.css

Fix issue fr fr now
https://github.com/JuiceMitApfelnDrin/CodinCod/pull/167

fix: non monospaced font in editor

---

libs/frontend/src/hooks.server.ts

fix: charset seo issue

---

libs/frontend/src/app.css
libs/frontend/src/lib/components/nav/navigation/navigation.svelte
libs/frontend/src/lib/components/ui/highlight-text/highlight-text.svelte
libs/frontend/src/routes/(authenticated)/multiplayer/[id]/+page.svelte
libs/types/src/core/puzzle/schema/puzzle-entity.schema.ts

fix: object object caused by result

---

libs/frontend/src/lib/features/puzzles/components/play-puzzle.svelte

percentages were show as `11.111111111111111%`, now it should be `11%`
partial fix of issues mentioned in: https://github.com/JuiceMitApfelnDrin/CodinCod/issues/78

fix: puzzle tests ran percentage

---

libs/frontend/.gitignore
libs/frontend/src/lib/components/nav/navigation/navigation-item.svelte
libs/frontend/src/lib/components/nav/navigation/navigation.svelte
libs/frontend/src/lib/components/nav/pagination.svelte
libs/frontend/src/lib/components/nav/toggle-theme.svelte
libs/frontend/src/lib/components/nav/user-dropdown.svelte
libs/frontend/src/lib/config/test-ids.ts
libs/frontend/src/lib/features/authentication/login/components/login-form.svelte
libs/frontend/src/routes/puzzles/+page.svelte

Fix navigation issue and introduce testids

feat: introduce test ids

---

libs/frontend/src/content/learn/markdown/README.md
libs/frontend/src/lib/features/learn/components/become-a-contributor.svelte

add markdown simple learn content

feat: add markdown simple learn content

---

libs/frontend/src/content/learn/markdown/README.md

small fix to markdown learning content

fix: markdown learning content

---

libs/backend/src/routes/puzzle/[id]/index.ts
libs/backend/src/utils/functions/check-all-validators.ts

feat: add auto puzzle visibility switching

---

libs/backend/src/config/generic-return-messages.ts
libs/backend/src/index.ts
libs/backend/src/plugins/middleware/authenticated.ts
libs/backend/src/plugins/middleware/decode-token.ts
libs/backend/src/router.ts
libs/backend/src/routes/puzzle/[id]/index.ts
libs/backend/src/routes/user/[username]/activity/index.ts
libs/backend/src/routes/user/[username]/puzzle/index.ts
libs/frontend/src/lib/config/api.ts
libs/frontend/src/lib/config/test-ids.ts
libs/frontend/src/lib/features/puzzles/components/edit-puzzle-form.svelte
libs/frontend/src/lib/stores/languages.ts
libs/frontend/src/routes/(authenticated)/puzzles/[id]/edit/+page.svelte
libs/frontend/src/routes/+error.svelte
libs/frontend/src/routes/api/user/[username]/puzzle/+server.ts
libs/frontend/src/routes/profile/[username]/puzzles/+page.server.ts
libs/frontend/src/routes/profile/[username]/puzzles/+page.svelte
libs/frontend/src/routes/puzzles/[id]/+page.server.ts
libs/types/src/core/common/config/backend-urls.ts
libs/types/src/core/common/config/frontend-urls.ts
libs/types/src/core/game/schema/waiting-room-request.schema.ts
libs/types/src/core/puzzle/config/puzzle-config.ts

feat: add profile username puzzles page

---

libs/frontend/src/routes/api/user/[username]/puzzle/+server.ts
libs/frontend/src/routes/puzzles/+page.svelte

pagination was broken on just created page

fix: issue with pagination

---

libs/frontend/src/routes/+layout.svelte
pnpm-lock.yaml

fix: main around all pages

---

libs/backend/tsconfig.json
libs/frontend/src/lib/components/error/display-error.svelte
libs/frontend/src/lib/components/nav/navigation/navigation.svelte
libs/frontend/src/lib/components/nav/user-dropdown.svelte
libs/frontend/src/lib/components/ui/button/button.svelte
libs/frontend/src/lib/components/ui/form/form-button.svelte
libs/frontend/src/lib/config/test-ids.ts
libs/frontend/src/lib/features/authentication/register/components/register-form.svelte
libs/frontend/src/lib/features/chat/components/chat.svelte
libs/frontend/src/lib/features/comment/components/add-comment-form.svelte
libs/frontend/src/lib/features/comment/components/comment.svelte
libs/frontend/src/lib/features/game/standings/components/standings-table.svelte
libs/frontend/src/lib/features/learn/components/become-a-contributor.svelte
libs/frontend/src/lib/features/puzzles/components/create-puzzle-form.svelte
libs/frontend/src/lib/features/puzzles/components/delete-puzzle-confirmation-dialog.svelte
libs/frontend/src/lib/features/puzzles/components/edit-puzzle-form.svelte
libs/frontend/src/lib/features/puzzles/components/play-puzzle.svelte
libs/frontend/src/lib/features/puzzles/components/user-hover-card.svelte
libs/frontend/src/routes/(authenticated)/multiplayer/+page.svelte
libs/frontend/src/routes/(authenticated)/multiplayer/[id]/+page.svelte
libs/frontend/src/routes/+error.svelte
libs/frontend/src/routes/profile/[username]/puzzles/+page.svelte
libs/frontend/src/routes/puzzles/[id]/+page.svelte
libs/frontend/svelte.config.js

Make testid on button mandatory

---

libs/backend/Dockerfile
libs/frontend/Dockerfile
libs/frontend/src/lib/components/nav/user-dropdown.svelte
libs/types/package.json
libs/types/src/core/common/schema/object-id.ts
pnpm-lock.yaml

The build process was broken due to a mongoose instance being imported in the frontend, apparently mongoose is backend only, so i diverted checking for objectid's from mongoose in types, to bson

fix: docker build process

---

libs/frontend/src/app.css
libs/frontend/src/lib/components/nav/user-dropdown.svelte
libs/frontend/src/lib/components/ui/avatar/avatar-fallback.svelte
libs/frontend/src/routes/+page.svelte
libs/frontend/src/routes/learn/+page.svelte
libs/frontend/src/routes/profile/[username]/puzzles/+page.svelte
libs/frontend/src/routes/puzzles/+page.svelte

links on homepage, smiley as avatar fallback, ...

fix: minor issues after upgrade svelte 5

---

libs/frontend/src/lib/components/nav/side-navigation/side-navigation-group.svelte
libs/frontend/src/lib/components/nav/side-navigation/side-navigation-item.svelte

due to migration changes, page didn't load no more, this fixes the issue with the component

fix: docs pages
